window.CRR_SURGERY_RECORDS = [
  {
    "id": "I0001186509",
    "date": "2026-05-26",
    "patient": "KENIA YARITZA PONCE OBANDO",
    "age": "30a 2m 12d",
    "diagnosis": "",
    "surgery": "LAPAROTOMIA EXPLORADORA, C/S LIBERACION DE ADHERENCIAS, C/S DRENAJE, C/S BIOPSIAS COMO PROC. AUT. O COMO RESULTADO DE UNA HERIDA PENETRANTE ABDOMINAL NO COMPLICADA O DE UN HEMOPERITONEO POSTOPERATORIO O COMO TRATAMIENTO",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Javier Ontiveros Ramirez (Protocolo Operatorio)",
    "surgeon": "Javiera Suarez Espinosa",
    "room": "Quirofano 16",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "00:05",
    "surgeryStart": "01:00",
    "surgeryEnd": "04:50",
    "exitTime": "05:35",
    "entryDelayMin": 55,
    "actualSurgeryMin": 230,
    "roomDurationMin": 330
  },
  {
    "id": "I0001187898",
    "date": "2026-05-26",
    "patient": "ALONSO JAVIER MENA SANDOVAL",
    "age": "14a 1m 3d",
    "diagnosis": "",
    "surgery": "APENDICECTOMIA Y/O DREN. ABSCESO APENDICULAR (PROC. AUT.)",
    "specialty": "Sin especialidad",
    "anesthetist": "Javier Ontiveros Ramirez (Protocolo Operatorio)",
    "surgeon": "Diego Ahumada Perez",
    "room": "Quirofano 04",
    "type": "Cirugía Urgencia",
    "status": "Atendido",
    "entryTime": "00:46",
    "surgeryStart": "01:14",
    "surgeryEnd": "03:24",
    "exitTime": "03:40",
    "entryDelayMin": 28,
    "actualSurgeryMin": 130,
    "roomDurationMin": 174
  },
  {
    "id": "I0001187897",
    "date": "2026-05-26",
    "patient": "NN-25/05/2026 14:23:58 NN-25/05/2026 14:23:58 NN-25/05/2026 14:23:58",
    "age": "61a 5m 22d",
    "diagnosis": "",
    "surgery": "Tratamiento completo de fracturas expuestas de mano o pie, c/u",
    "specialty": "TRAUMATOLOGIA Y ORTOPEDÍA",
    "anesthetist": "Marcela Verónica Ortiz Acheritogaray (Protocolo Operatorio)",
    "surgeon": "Carlos Espino Espino",
    "room": "Quirofano 04",
    "type": "Cirugía Urgencia",
    "status": "Atendido",
    "entryTime": "04:44",
    "surgeryStart": "05:20",
    "surgeryEnd": "06:35",
    "exitTime": "06:40",
    "entryDelayMin": 36,
    "actualSurgeryMin": 75,
    "roomDurationMin": 116
  },
  {
    "id": "I0001187867",
    "date": "2026-05-26",
    "patient": "MARIANA ANGELICA CABELLO ALEJOS",
    "age": "19a 9m 25d",
    "diagnosis": "",
    "surgery": "CESAREA",
    "specialty": "GINECOLOGIA",
    "anesthetist": "Marcela Verónica Ortiz Acheritogaray (Protocolo Operatorio)",
    "surgeon": "Natalia Homm Jara",
    "room": "Quirofano 03",
    "type": "Cirugía Urgencia",
    "status": "Realizado",
    "entryTime": "05:17",
    "surgeryStart": "05:37",
    "surgeryEnd": "06:47",
    "exitTime": "",
    "entryDelayMin": 20,
    "actualSurgeryMin": 70,
    "roomDurationMin": ""
  },
  {
    "id": "I0001187799",
    "date": "2026-05-26",
    "patient": "FIDEL EUGENIO CÁCERES SAGREDO",
    "age": "66a 4m 20d",
    "diagnosis": "",
    "surgery": "Nefrectomía parcial cualquier vía y técnica. Incluye disección ganglionar etapificadora o reductiva",
    "specialty": "UROLOGIA",
    "anesthetist": "Marcos Barcia Veintimilla (Protocolo Operatorio)",
    "surgeon": "Mario Hassi Roman",
    "room": "Quirofano 01",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "08:15",
    "surgeryStart": "09:30",
    "surgeryEnd": "12:50",
    "exitTime": "13:25",
    "entryDelayMin": 75,
    "actualSurgeryMin": 200,
    "roomDurationMin": 310
  },
  {
    "id": "I0001187815",
    "date": "2026-05-26",
    "patient": "LUIS OSVALDO FERNAND FRITES CABAÑA",
    "age": "81a 11m 6d",
    "diagnosis": "",
    "surgery": "AMPUTACIÓN PIERNA",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Isidora Fernanda Gonzalez Arenas (Protocolo Operatorio)",
    "surgeon": "Dr. Roberto Figueroa Valenzuela",
    "room": "Quirofano 07",
    "type": "Cirugía Electiva",
    "status": "Agendado",
    "entryTime": "08:25",
    "surgeryStart": "09:10",
    "surgeryEnd": "09:50",
    "exitTime": "10:05",
    "entryDelayMin": 45,
    "actualSurgeryMin": 40,
    "roomDurationMin": 100
  },
  {
    "id": "I0001187721",
    "date": "2026-05-26",
    "patient": "PAOLA ANDREA OLGUÍN MORA",
    "age": "57a 6m 11d",
    "diagnosis": "",
    "surgery": "COLECISTECTOMIA POR VIDEOLAPAROSCOPIA, PROC. COMPLETO",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Aliana Violeta Morales Ruiz (Protocolo Anestésico)",
    "surgeon": "Felicia Meza Maldonado",
    "room": "Quirofano 09",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "08:27",
    "surgeryStart": "09:18",
    "surgeryEnd": "09:54",
    "exitTime": "10:27",
    "entryDelayMin": 51,
    "actualSurgeryMin": 36,
    "roomDurationMin": 120
  },
  {
    "id": "I0001187827",
    "date": "2026-05-26",
    "patient": "MICHAEL NICOLAS MARIN MUÑOZ",
    "age": "22a 0m 18d",
    "diagnosis": "",
    "surgery": "FRACTURA DE CLAVICULA, OSTEOSINTESIS",
    "specialty": "TRAUMATOLOGIA Y ORTOPEDÍA",
    "anesthetist": "Reina Garrido Trejo (Protocolo Operatorio)",
    "surgeon": "Claudio Gonzalez Pineda",
    "room": "Quirofano 15",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "08:30",
    "surgeryStart": "09:40",
    "surgeryEnd": "11:00",
    "exitTime": "11:45",
    "entryDelayMin": 70,
    "actualSurgeryMin": 80,
    "roomDurationMin": 195
  },
  {
    "id": "I0001187788",
    "date": "2026-05-26",
    "patient": "BALTAZAR LEON PAILLAVIL SOTO",
    "age": "3a 3m 5d",
    "diagnosis": "",
    "surgery": "AMIGDALECTOMIA C/S ADENOIDECTOMIA, UNI O BILATERAL",
    "specialty": "OTORRINOLARINGOLOGIA",
    "anesthetist": "Rodrigo Alejandro Villegas Lugo (Protocolo Operatorio)",
    "surgeon": "Dr. Cristian Aedo Bendel",
    "room": "Quirofano 06",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "08:32",
    "surgeryStart": "09:05",
    "surgeryEnd": "09:25",
    "exitTime": "10:15",
    "entryDelayMin": 33,
    "actualSurgeryMin": 20,
    "roomDurationMin": 103
  },
  {
    "id": "I0001187821",
    "date": "2026-05-26",
    "patient": "VICENTE ANTONIO QUIROZ QUIROZ",
    "age": "56a 9m 14d",
    "diagnosis": "",
    "surgery": "RECONSTITUCION TRANSITO POST OPERACION DE HARTMANN O SIM.",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Jeraldo Triantafilo Schilling (Protocolo Anestésico); Jeraldo Triantafilo Schilling (Protocolo Operatorio)",
    "surgeon": "Dra. Marisol Noriel Valdes",
    "room": "Quirofano 11",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "08:32",
    "surgeryStart": "09:13",
    "surgeryEnd": "12:41",
    "exitTime": "13:10",
    "entryDelayMin": 41,
    "actualSurgeryMin": 208,
    "roomDurationMin": 278
  },
  {
    "id": "I0001187685",
    "date": "2026-05-26",
    "patient": "MEHILIN LOPEZ ESPINOZA",
    "age": "18a 0m 21d",
    "diagnosis": "",
    "surgery": "CESAREA",
    "specialty": "Sin especialidad",
    "anesthetist": "Jorge Lizama Leon (Protocolo Operatorio)",
    "surgeon": "Elio Arturo Zapata Velasquez",
    "room": "Quirofano 03",
    "type": "Cirugía Urgencia",
    "status": "Realizado",
    "entryTime": "08:37",
    "surgeryStart": "08:57",
    "surgeryEnd": "09:26",
    "exitTime": "09:39",
    "entryDelayMin": 20,
    "actualSurgeryMin": 29,
    "roomDurationMin": 62
  },
  {
    "id": "I0001187831",
    "date": "2026-05-26",
    "patient": "FELIPE ANTONIO MOLINA CHEUQUEÑANCO",
    "age": "17a 4m 25d",
    "diagnosis": "",
    "surgery": "OSTEOSINTESIS RADIO, (CUALQUIER TECNICA)",
    "specialty": "Sin especialidad",
    "anesthetist": "Joaquin Lopez Muñoz (Protocolo Operatorio)",
    "surgeon": "Paula Ramírez Vargas",
    "room": "Quirofano 13",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "08:38",
    "surgeryStart": "09:20",
    "surgeryEnd": "10:45",
    "exitTime": "11:06",
    "entryDelayMin": 42,
    "actualSurgeryMin": 85,
    "roomDurationMin": 148
  },
  {
    "id": "I0001187933",
    "date": "2026-05-26",
    "patient": "MARYGRELIS DEL VALLE GOMEZ GIL",
    "age": "27a 10m 14d",
    "diagnosis": "",
    "surgery": "COLECISTECTOMIA C/S COLANGIOGRAFIA OPERATORIA",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Jackeline Nuñez (Protocolo Anestésico); Jackeline Nuñez (Protocolo Operatorio)",
    "surgeon": "Dr Alvaro Mendoza Fernandez",
    "room": "Quirofano 16",
    "type": "Cirugía Urgencia",
    "status": "Realizado",
    "entryTime": "08:40",
    "surgeryStart": "09:10",
    "surgeryEnd": "10:05",
    "exitTime": "10:17",
    "entryDelayMin": 30,
    "actualSurgeryMin": 55,
    "roomDurationMin": 97
  },
  {
    "id": "I0001187807",
    "date": "2026-05-26",
    "patient": "CECILIA LORENA MUÑOZ MUÑOZ",
    "age": "72a 9m 22d",
    "diagnosis": "",
    "surgery": "Histerectomía total o ampliada por vía abdominal",
    "specialty": "GINECOLOGIA",
    "anesthetist": "Nelson Gonzalez Doria (Protocolo Operatorio)",
    "surgeon": "Ignacio Chavez Rodriguez",
    "room": "Quirofano 12",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "08:45",
    "surgeryStart": "09:53",
    "surgeryEnd": "12:30",
    "exitTime": "12:57",
    "entryDelayMin": 68,
    "actualSurgeryMin": 157,
    "roomDurationMin": 252
  },
  {
    "id": "I0001187729",
    "date": "2026-05-26",
    "patient": "LUIS EDUARDO AVENDAÑO ROMÁN",
    "age": "71a 6m 12d",
    "diagnosis": "",
    "surgery": "Adenoma o cáncer prostático, resección endoscópica desobstructiva, cualquier técnica (uni, bipolar, láser u otros)",
    "specialty": "UROLOGIA",
    "anesthetist": "",
    "surgeon": "José Ignacio Acuña Madrid",
    "room": "Quirofano 10",
    "type": "Cirugía Electiva",
    "status": "Realizado",
    "entryTime": "08:47",
    "surgeryStart": "10:00",
    "surgeryEnd": "10:30",
    "exitTime": "10:58",
    "entryDelayMin": 73,
    "actualSurgeryMin": 30,
    "roomDurationMin": 131
  },
  {
    "id": "I0001187769",
    "date": "2026-05-26",
    "patient": "YEDRIT ARMANDINA VILLA VALDEBENITO",
    "age": "68a 3m 11d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Ingrid Josette Baudoin Loayza (Protocolo Operatorio)",
    "surgeon": "Claudio Araya Cargas",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "08:50",
    "surgeryStart": "08:58",
    "surgeryEnd": "09:29",
    "exitTime": "09:31",
    "entryDelayMin": 8,
    "actualSurgeryMin": 31,
    "roomDurationMin": 41
  },
  {
    "id": "I0001185830",
    "date": "2026-05-26",
    "patient": "GASPAR VALENTINO MONTESINOS SANTIBAÑEZ",
    "age": "10a 8m 3d",
    "diagnosis": "",
    "surgery": "Curación por Médico, Quemadura o Similar menor al 5% superficie corporal en pabellón",
    "specialty": "CIRUGIA PLASTICA Y REPARADORA PEDIATRICA",
    "anesthetist": "Gianna Muñoz (Protocolo Operatorio)",
    "surgeon": "Paula Contreras Perines",
    "room": "Quirofano 05",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "08:55",
    "surgeryStart": "09:15",
    "surgeryEnd": "10:20",
    "exitTime": "10:58",
    "entryDelayMin": 20,
    "actualSurgeryMin": 65,
    "roomDurationMin": 123
  },
  {
    "id": "I0001187883",
    "date": "2026-05-26",
    "patient": "LEONARDO BENJAMIN SALVADOR FLORES VIZCARRA",
    "age": "1a 5m 28d",
    "diagnosis": "",
    "surgery": "ESCARECTOMIA- HASTA 1 % SUPERFICIE CORPORAL",
    "specialty": "CIRUGIA PEDIATRICA",
    "anesthetist": "Margarita Rojas Espinoza (Protocolo Operatorio)",
    "surgeon": "Aileen Ferran Ferran Sepulveda",
    "room": "Quirofano 04",
    "type": "Cirugía Urgencia",
    "status": "Atendido",
    "entryTime": "09:20",
    "surgeryStart": "09:45",
    "surgeryEnd": "10:10",
    "exitTime": "10:50",
    "entryDelayMin": 25,
    "actualSurgeryMin": 25,
    "roomDurationMin": 90
  },
  {
    "id": "I0001187770",
    "date": "2026-05-26",
    "patient": "SEGUNDO OSVALDO ROSALES ORTEGA",
    "age": "72a 1m 8d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Ingrid Josette Baudoin Loayza (Protocolo Operatorio)",
    "surgeon": "Claudio Araya Cargas",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "09:36",
    "surgeryStart": "09:43",
    "surgeryEnd": "09:59",
    "exitTime": "10:03",
    "entryDelayMin": 7,
    "actualSurgeryMin": 16,
    "roomDurationMin": 27
  },
  {
    "id": "I0001187754",
    "date": "2026-05-26",
    "patient": "LUISA DEL CARMEN ROJAS ARÁNGUIZ",
    "age": "45a 2m 16d",
    "diagnosis": "",
    "surgery": "Histerectomía total o ampliada por vía abdominal",
    "specialty": "GINECOLOGIA",
    "anesthetist": "Jorge Lizama Leon (Protocolo Operatorio)",
    "surgeon": "Juan Rodriguez Ticona",
    "room": "Quirofano 02",
    "type": "Cirugía Electiva",
    "status": "Realizado",
    "entryTime": "09:45",
    "surgeryStart": "10:13",
    "surgeryEnd": "11:43",
    "exitTime": "",
    "entryDelayMin": 28,
    "actualSurgeryMin": 90,
    "roomDurationMin": ""
  },
  {
    "id": "I0001187771",
    "date": "2026-05-26",
    "patient": "OLGA DE JESÚS GALLARDO AGUIRRE",
    "age": "84a 5m 11d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Ingrid Josette Baudoin Loayza (Protocolo Operatorio)",
    "surgeon": "Claudio Araya Cargas",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "10:10",
    "surgeryStart": "10:15",
    "surgeryEnd": "10:28",
    "exitTime": "10:31",
    "entryDelayMin": 5,
    "actualSurgeryMin": 13,
    "roomDurationMin": 21
  },
  {
    "id": "I0001183148",
    "date": "2026-05-26",
    "patient": "PABLO FELIPE CELIS ALBORNOZ",
    "age": "52a 6m 4d",
    "diagnosis": "",
    "surgery": "AMPUTACIÓN PIERNA",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Isidora Fernanda Gonzalez Arenas (Protocolo Operatorio)",
    "surgeon": "Jose Antonio Terán Fuenmayor",
    "room": "Quirofano 07",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "10:26",
    "surgeryStart": "11:00",
    "surgeryEnd": "11:35",
    "exitTime": "12:00",
    "entryDelayMin": 34,
    "actualSurgeryMin": 35,
    "roomDurationMin": 94
  },
  {
    "id": "I0001187772",
    "date": "2026-05-26",
    "patient": "MIREYA ALARCÓN ORTEGA",
    "age": "82a 11m 16d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Ingrid Josette Baudoin Loayza (Protocolo Operatorio)",
    "surgeon": "Claudio Araya Cargas",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "10:39",
    "surgeryStart": "10:44",
    "surgeryEnd": "11:05",
    "exitTime": "11:09",
    "entryDelayMin": 5,
    "actualSurgeryMin": 21,
    "roomDurationMin": 30
  },
  {
    "id": "I0001187790",
    "date": "2026-05-26",
    "patient": "JARED VALENTINO SALINAS CRUZ",
    "age": "6a 0m 1d",
    "diagnosis": "",
    "surgery": "AMIGDALECTOMIA C/S ADENOIDECTOMIA, UNI O BILATERAL",
    "specialty": "OTORRINOLARINGOLOGIA",
    "anesthetist": "Rodrigo Alejandro Villegas Lugo (Protocolo Operatorio)",
    "surgeon": "Dr. Cristian Aedo Bendel",
    "room": "Quirofano 06",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "10:40",
    "surgeryStart": "11:00",
    "surgeryEnd": "12:00",
    "exitTime": "12:15",
    "entryDelayMin": 20,
    "actualSurgeryMin": 60,
    "roomDurationMin": 95
  },
  {
    "id": "I0001187723",
    "date": "2026-05-26",
    "patient": "JUANA ROSA FLORES HIDALGO",
    "age": "43a 9m 11d",
    "diagnosis": "",
    "surgery": "COLECISTECTOMIA POR VIDEOLAPAROSCOPIA, PROC. COMPLETO",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Aliana Violeta Morales Ruiz (Protocolo Anestésico); Aliana Violeta Morales Ruiz (Protocolo Operatorio)",
    "surgeon": "Carleny Cordero Lugo",
    "room": "Quirofano 09",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "10:40",
    "surgeryStart": "11:15",
    "surgeryEnd": "12:00",
    "exitTime": "12:30",
    "entryDelayMin": 35,
    "actualSurgeryMin": 45,
    "roomDurationMin": 110
  },
  {
    "id": "I0001187894",
    "date": "2026-05-26",
    "patient": "JOSÉ FRANCISCO JAVIER GAMBOA POBLETE",
    "age": "33a 4m 9d",
    "diagnosis": "",
    "surgery": "APENDICECTOMIA Y/O DREN. ABSCESO APENDICULAR (PROC. AUT.)",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Jackeline Nuñez (Protocolo Anestésico)",
    "surgeon": "Dr. Rodrigo Martinez Lobos",
    "room": "Quirofano 16",
    "type": "Cirugía Urgencia",
    "status": "Realizado",
    "entryTime": "10:42",
    "surgeryStart": "11:10",
    "surgeryEnd": "11:40",
    "exitTime": "",
    "entryDelayMin": 28,
    "actualSurgeryMin": 30,
    "roomDurationMin": ""
  },
  {
    "id": "I0001187730",
    "date": "2026-05-26",
    "patient": "MANUEL OCTAVIO ALARCÓN GÁLVEZ",
    "age": "84a 0m 9d",
    "diagnosis": "",
    "surgery": "Adenoma o cáncer prostático, resección endoscópica desobstructiva, cualquier técnica (uni, bipolar, láser u otros)",
    "specialty": "UROLOGIA",
    "anesthetist": "",
    "surgeon": "José Ignacio Acuña Madrid",
    "room": "Quirofano 10",
    "type": "Cirugía Electiva",
    "status": "Realizado",
    "entryTime": "11:15",
    "surgeryStart": "11:52",
    "surgeryEnd": "14:05",
    "exitTime": "14:13",
    "entryDelayMin": 37,
    "actualSurgeryMin": 133,
    "roomDurationMin": 178
  },
  {
    "id": "I0001187773",
    "date": "2026-05-26",
    "patient": "GLORIA ANGÉLICA COSTA ULLOA",
    "age": "64a 7m 4d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Ingrid Josette Baudoin Loayza (Protocolo Operatorio)",
    "surgeon": "Claudio Araya Cargas",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "11:17",
    "surgeryStart": "11:23",
    "surgeryEnd": "11:38",
    "exitTime": "11:42",
    "entryDelayMin": 6,
    "actualSurgeryMin": 15,
    "roomDurationMin": 25
  },
  {
    "id": "I0001187934",
    "date": "2026-05-26",
    "patient": "ANGELA DEL CARMEN LÓPEZ DURÁN",
    "age": "53a 8m 4d",
    "diagnosis": "",
    "surgery": "COLECISTECTOMIA C/S COLANGIOGRAFIA OPERATORIA",
    "specialty": "Sin especialidad",
    "anesthetist": "Maria Elvira DE FEREIRA Acosta de Fereira (Protocolo Anestésico)",
    "surgeon": "Dr Alvaro Mendoza Fernandez",
    "room": "Quirofano 04",
    "type": "Cirugía Urgencia",
    "status": "Recepcionado",
    "entryTime": "11:35",
    "surgeryStart": "12:14",
    "surgeryEnd": "13:30",
    "exitTime": "13:55",
    "entryDelayMin": 39,
    "actualSurgeryMin": 76,
    "roomDurationMin": 140
  },
  {
    "id": "I0000992829",
    "date": "2026-05-26",
    "patient": "EYDHAN ANDRES GUZMAN ROJAS",
    "age": "2a 2m 29d",
    "diagnosis": "",
    "surgery": "GASTROTOMIA Y/O GASTROSTOMIA (PROC. AUT.)",
    "specialty": "GASTROENTEROLOGIA PEDIATRICA",
    "anesthetist": "Gianna Muñoz (Protocolo Operatorio)",
    "surgeon": "Julio Rodolfo Galarza Villacrés",
    "room": "Quirofano 05",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "11:35",
    "surgeryStart": "11:53",
    "surgeryEnd": "12:30",
    "exitTime": "13:00",
    "entryDelayMin": 18,
    "actualSurgeryMin": 37,
    "roomDurationMin": 85
  },
  {
    "id": "I0001187939",
    "date": "2026-05-26",
    "patient": "BENJAMIN ANTONIO VELOSO GONZÁLEZ",
    "age": "22a 3m 0d",
    "diagnosis": "",
    "surgery": "FRACTURA O PSEUDOARTROSIS ESCAFOIDES, TRAT. QUIR. CUALQ. TECN.",
    "specialty": "TRAUMATOLOGIA Y ORTOPEDÍA",
    "anesthetist": "Joaquin Lopez Muñoz (Protocolo Operatorio)",
    "surgeon": "Dr. Alexis Arredondo Torrales",
    "room": "Quirofano 13",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "12:07",
    "surgeryStart": "12:31",
    "surgeryEnd": "13:28",
    "exitTime": "13:41",
    "entryDelayMin": 24,
    "actualSurgeryMin": 57,
    "roomDurationMin": 94
  },
  {
    "id": "I0001187936",
    "date": "2026-05-26",
    "patient": "ELBA MARISOL MUÑOZ REYES",
    "age": "59a 1m 22d",
    "diagnosis": "",
    "surgery": "- Raspado uterino diagnóstico o terapéutico por metrorragia o por restos de aborto",
    "specialty": "GINECOLOGIA",
    "anesthetist": "Jorge Lizama Leon (Protocolo Operatorio)",
    "surgeon": "Tarek Saad Numan",
    "room": "Quirofano 03",
    "type": "Cirugía Electiva",
    "status": "Realizado",
    "entryTime": "12:12",
    "surgeryStart": "12:30",
    "surgeryEnd": "12:40",
    "exitTime": "12:52",
    "entryDelayMin": 18,
    "actualSurgeryMin": 10,
    "roomDurationMin": 40
  },
  {
    "id": "I0001187794",
    "date": "2026-05-26",
    "patient": "ÁNGEL ALEJANDRO CARIQUEO MARAMBIO",
    "age": "4a 9m 12d",
    "diagnosis": "",
    "surgery": "AMIGDALECTOMIA C/S ADENOIDECTOMIA, UNI O BILATERAL",
    "specialty": "OTORRINOLARINGOLOGIA",
    "anesthetist": "Rodrigo Alejandro Villegas Lugo (Protocolo Operatorio)",
    "surgeon": "Dr. Christian Diaz Frias",
    "room": "Quirofano 06",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "12:30",
    "surgeryStart": "12:52",
    "surgeryEnd": "13:26",
    "exitTime": "13:52",
    "entryDelayMin": 22,
    "actualSurgeryMin": 34,
    "roomDurationMin": 82
  },
  {
    "id": "I0001186511",
    "date": "2026-05-26",
    "patient": "MYRIAM LUZ RÍOS ESTRADA",
    "age": "52a 4m 5d",
    "diagnosis": "",
    "surgery": "OSTEOMIELITIS, LIMPIEZA QUIRURGICA",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Isidora Fernanda Gonzalez Arenas (Protocolo Operatorio)",
    "surgeon": "Dr. Roberto Figueroa Valenzuela",
    "room": "Quirofano 07",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "12:30",
    "surgeryStart": "13:18",
    "surgeryEnd": "14:05",
    "exitTime": "14:14",
    "entryDelayMin": 48,
    "actualSurgeryMin": 47,
    "roomDurationMin": 104
  },
  {
    "id": "I0001186882",
    "date": "2026-05-26",
    "patient": "JOSÉ EMILIANO CANALES RETAMALES",
    "age": "71a 1m 20d",
    "diagnosis": "",
    "surgery": "LAPAROTOMIA EXPLORADORA, C/S LIBERACION DE ADHERENCIAS, C/S DRENAJE, C/S BIOPSIAS COMO PROC. AUT. O COMO RESULTADO DE UNA HERIDA PENETRANTE ABDOMINAL NO COMPLICADA O DE UN HEMOPERITONEO POSTOPERATORIO O COMO TRATAMIENTO",
    "specialty": "Sin especialidad",
    "anesthetist": "Jackeline Nuñez (Protocolo Operatorio)",
    "surgeon": "Dr. Anibal Pinto Lara",
    "room": "Quirofano 16",
    "type": "Cirugía Urgencia",
    "status": "Realizado",
    "entryTime": "12:45",
    "surgeryStart": "13:15",
    "surgeryEnd": "14:30",
    "exitTime": "14:35",
    "entryDelayMin": 30,
    "actualSurgeryMin": 75,
    "roomDurationMin": 110
  },
  {
    "id": "I0001187725",
    "date": "2026-05-26",
    "patient": "MARÍA JOSÉ ARIAS VERA",
    "age": "41a 4m 13d",
    "diagnosis": "",
    "surgery": "COLECISTECTOMIA POR VIDEOLAPAROSCOPIA, PROC. COMPLETO",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Aliana Violeta Morales Ruiz (Protocolo Operatorio)",
    "surgeon": "Jesus Soublett Rivas",
    "room": "Quirofano 09",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "12:45",
    "surgeryStart": "13:20",
    "surgeryEnd": "14:20",
    "exitTime": "14:46",
    "entryDelayMin": 35,
    "actualSurgeryMin": 60,
    "roomDurationMin": 121
  },
  {
    "id": "I0001187930",
    "date": "2026-05-26",
    "patient": "CAROLINA ANGÉLICA CAMPOS CAMPOS",
    "age": "18a 3m 3d",
    "diagnosis": "",
    "surgery": "CESAREA",
    "specialty": "GINECOLOGIA",
    "anesthetist": "Margarita Rojas Espinoza (Protocolo Operatorio)",
    "surgeon": "Juan Rodriguez Ticona",
    "room": "Quirofano 02",
    "type": "Cirugía Electiva",
    "status": "Realizado",
    "entryTime": "12:57",
    "surgeryStart": "13:19",
    "surgeryEnd": "13:56",
    "exitTime": "14:00",
    "entryDelayMin": 22,
    "actualSurgeryMin": 37,
    "roomDurationMin": 63
  },
  {
    "id": "I0000992829",
    "date": "2026-05-26",
    "patient": "EYDHAN ANDRES GUZMAN ROJAS",
    "age": "2a 2m 29d",
    "diagnosis": "",
    "surgery": "Instalación de catéter venoso de larga duración tunelizado (incluye cateter)",
    "specialty": "Sin especialidad",
    "anesthetist": "Gianna Muñoz (Protocolo Operatorio)",
    "surgeon": "Aileen Ferran Ferran Sepulveda",
    "room": "Quirofano 05",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "13:10",
    "surgeryStart": "13:20",
    "surgeryEnd": "14:37",
    "exitTime": "14:50",
    "entryDelayMin": 10,
    "actualSurgeryMin": 77,
    "roomDurationMin": 100
  },
  {
    "id": "I0001187963",
    "date": "2026-05-26",
    "patient": "FERNANDO MARCELO ZAPATA MUÑOZ",
    "age": "56a 5m 28d",
    "diagnosis": "",
    "surgery": "ESCARECTOMIA- HASTA 1 % SUPERFICIE CORPORAL",
    "specialty": "Sin especialidad",
    "anesthetist": "Reina Garrido Trejo (Protocolo Anestésico)",
    "surgeon": "Sebastián Pinto Padilla",
    "room": "Quirofano 15",
    "type": "Cirugía Electiva",
    "status": "Realizado",
    "entryTime": "13:30",
    "surgeryStart": "14:00",
    "surgeryEnd": "14:45",
    "exitTime": "15:10",
    "entryDelayMin": 30,
    "actualSurgeryMin": 45,
    "roomDurationMin": 100
  },
  {
    "id": "I0001187822",
    "date": "2026-05-26",
    "patient": "JUAN BAUTISTA ASTORGA FUENTES",
    "age": "75a 3m 3d",
    "diagnosis": "",
    "surgery": "RECONSTITUCION TRANSITO POST OPERACION DE HARTMANN O SIM.",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Jeraldo Triantafilo Schilling (Protocolo Operatorio)",
    "surgeon": "Erika Chacon Dittus",
    "room": "Quirofano 11",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "13:32",
    "surgeryStart": "14:06",
    "surgeryEnd": "15:00",
    "exitTime": "15:22",
    "entryDelayMin": 34,
    "actualSurgeryMin": 54,
    "roomDurationMin": 110
  },
  {
    "id": "I0001187800",
    "date": "2026-05-26",
    "patient": "CLARISA DEL CARMEN ROSALES ORTEGA",
    "age": "68a 4m 20d",
    "diagnosis": "",
    "surgery": "Nefrectomía parcial cualquier vía y técnica. Incluye disección ganglionar etapificadora o reductiva",
    "specialty": "UROLOGIA",
    "anesthetist": "Marcos Barcia Veintimilla (Protocolo Operatorio)",
    "surgeon": "Mario Hassi Roman",
    "room": "Quirofano 01",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "13:40",
    "surgeryStart": "15:02",
    "surgeryEnd": "17:26",
    "exitTime": "17:40",
    "entryDelayMin": 82,
    "actualSurgeryMin": 144,
    "roomDurationMin": 240
  },
  {
    "id": "I0001187832",
    "date": "2026-05-26",
    "patient": "MÓNICA VALESKA GONZÁLEZ DONOSO",
    "age": "51a 9m 29d",
    "diagnosis": "",
    "surgery": "OSTEOSINTESIS, FRACT. CERRADA CUBITO Y/O RADIO (CUALQ. TECN.)",
    "specialty": "Sin especialidad",
    "anesthetist": "Joaquin Lopez Muñoz (Protocolo Operatorio)",
    "surgeon": "Dr. Alexis Arredondo Torrales",
    "room": "Quirofano 13",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "14:06",
    "surgeryStart": "14:42",
    "surgeryEnd": "15:25",
    "exitTime": "15:38",
    "entryDelayMin": 36,
    "actualSurgeryMin": 43,
    "roomDurationMin": 92
  },
  {
    "id": "I0001187811",
    "date": "2026-05-26",
    "patient": "HELEN DEL CARMEN CANTILLANA LAZO",
    "age": "50a 9m 27d",
    "diagnosis": "",
    "surgery": "Histerectomía total o ampliada por vía abdominal",
    "specialty": "GINECOLOGIA",
    "anesthetist": "Nelson Gonzalez Doria (Protocolo Anestésico)",
    "surgeon": "Victoria Toro Silva",
    "room": "Quirofano 12",
    "type": "Cirugía Electiva",
    "status": "Realizado",
    "entryTime": "14:25",
    "surgeryStart": "15:10",
    "surgeryEnd": "16:30",
    "exitTime": "16:52",
    "entryDelayMin": 45,
    "actualSurgeryMin": 80,
    "roomDurationMin": 147
  },
  {
    "id": "I0001187868",
    "date": "2026-05-26",
    "patient": "CARMEN GLORIA PAINEQUIR CONSTANZO",
    "age": "47a 3m 9d",
    "diagnosis": "",
    "surgery": "CESAREA",
    "specialty": "Sin especialidad",
    "anesthetist": "",
    "surgeon": "Facundo Henriquez Lagos",
    "room": "Quirofano 03",
    "type": "Cirugía Electiva",
    "status": "Realizado",
    "entryTime": "14:25",
    "surgeryStart": "14:48",
    "surgeryEnd": "15:33",
    "exitTime": "15:48",
    "entryDelayMin": 23,
    "actualSurgeryMin": 45,
    "roomDurationMin": 83
  },
  {
    "id": "I0001187777",
    "date": "2026-05-26",
    "patient": "SILVIA DEL CARMEN GONZÁLEZ FRÍAS",
    "age": "78a 6m 23d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Ingrid Josette Baudoin Loayza (Protocolo Operatorio)",
    "surgeon": "Mauricio Andres Perez Gonzales",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "14:30",
    "surgeryStart": "14:40",
    "surgeryEnd": "15:12",
    "exitTime": "15:15",
    "entryDelayMin": 10,
    "actualSurgeryMin": 32,
    "roomDurationMin": 45
  },
  {
    "id": "I0001187796",
    "date": "2026-05-26",
    "patient": "AYELEN TRINIDAD GONZÁLEZ SOTO",
    "age": "11a 1m 28d",
    "diagnosis": "",
    "surgery": "ADENOIDECTOMIA (PROC. AUT.)",
    "specialty": "OTORRINOLARINGOLOGIA",
    "anesthetist": "Rodrigo Alejandro Villegas Lugo (Protocolo Operatorio)",
    "surgeon": "Dr. Christian Diaz Frias",
    "room": "Quirofano 06",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "14:40",
    "surgeryStart": "14:55",
    "surgeryEnd": "15:23",
    "exitTime": "15:40",
    "entryDelayMin": 15,
    "actualSurgeryMin": 28,
    "roomDurationMin": 60
  },
  {
    "id": "I0001187731",
    "date": "2026-05-26",
    "patient": "ERNESTO ARTEMIO GUTIÉRREZ LEAL",
    "age": "77a 5m 23d",
    "diagnosis": "",
    "surgery": "Adenoma o cáncer prostático, resección endoscópica desobstructiva, cualquier técnica (uni, bipolar, láser u otros)",
    "specialty": "UROLOGIA",
    "anesthetist": "",
    "surgeon": "José Ignacio Acuña Madrid",
    "room": "Quirofano 10",
    "type": "Cirugía Electiva",
    "status": "Realizado",
    "entryTime": "14:56",
    "surgeryStart": "15:29",
    "surgeryEnd": "16:00",
    "exitTime": "16:10",
    "entryDelayMin": 33,
    "actualSurgeryMin": 31,
    "roomDurationMin": 74
  },
  {
    "id": "I0001187724",
    "date": "2026-05-26",
    "patient": "JESSICA ROSARIO NORAMBUENA CERÓN",
    "age": "48a 5m 9d",
    "diagnosis": "",
    "surgery": "COLECISTECTOMIA POR VIDEOLAPAROSCOPIA, PROC. COMPLETO",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Aliana Violeta Morales Ruiz (Protocolo Anestésico)",
    "surgeon": "Gonzalo Godoy Moya",
    "room": "Quirofano 09",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "15:00",
    "surgeryStart": "15:38",
    "surgeryEnd": "16:14",
    "exitTime": "16:37",
    "entryDelayMin": 38,
    "actualSurgeryMin": 36,
    "roomDurationMin": 97
  },
  {
    "id": "I0001187819",
    "date": "2026-05-26",
    "patient": "EDUARDO ENRIQUE RODRÍGUEZ REYES",
    "age": "67a 3m 15d",
    "diagnosis": "",
    "surgery": "Hernioplastía diafragmática por vía torácica c/s prótesis por vía videotoracoscopica",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Isidora Fernanda Gonzalez Arenas (Protocolo Operatorio)",
    "surgeon": "Dr. Roberto Figueroa Valenzuela",
    "room": "Quirofano 07",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "15:15",
    "surgeryStart": "15:47",
    "surgeryEnd": "16:50",
    "exitTime": "16:58",
    "entryDelayMin": 32,
    "actualSurgeryMin": 63,
    "roomDurationMin": 103
  },
  {
    "id": "I0001182289",
    "date": "2026-05-26",
    "patient": "AMELIA MORA ARELLANO",
    "age": "82a 10m 16d",
    "diagnosis": "",
    "surgery": "OSTEOMIELITIS, LIMPIEZA QUIRURGICA",
    "specialty": "TRAUMATOLOGIA Y ORTOPEDÍA",
    "anesthetist": "Reina Garrido Trejo (Protocolo Operatorio)",
    "surgeon": "Sebastián Pinto Padilla",
    "room": "Quirofano 15",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "15:20",
    "surgeryStart": "15:55",
    "surgeryEnd": "16:25",
    "exitTime": "",
    "entryDelayMin": 35,
    "actualSurgeryMin": 30,
    "roomDurationMin": ""
  },
  {
    "id": "I0001187775",
    "date": "2026-05-26",
    "patient": "DANIELA CECILIA ALBORNOZ FERRER",
    "age": "44a 3m 25d",
    "diagnosis": "",
    "surgery": "GLAUCOMA, TRAT. QUIR. POR CUALQUIER TECNICA",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Ingrid Josette Baudoin Loayza (Protocolo Operatorio)",
    "surgeon": "Mauricio Andres Perez Gonzales",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "15:25",
    "surgeryStart": "15:35",
    "surgeryEnd": "16:40",
    "exitTime": "16:44",
    "entryDelayMin": 10,
    "actualSurgeryMin": 65,
    "roomDurationMin": 79
  },
  {
    "id": "I0001187955",
    "date": "2026-05-26",
    "patient": "VICENTE ALEXANDER BRAVO GALLEGOS",
    "age": "12a 10m 21d",
    "diagnosis": "",
    "surgery": "APENDICECTOMIA Y/O DREN. ABSCESO APENDICULAR (PROC. AUT.)",
    "specialty": "CIRUGIA PEDIATRICA",
    "anesthetist": "Margarita Rojas Espinoza (Protocolo Operatorio)",
    "surgeon": "Aileen Ferran Ferran Sepulveda",
    "room": "Quirofano 04",
    "type": "Cirugía Urgencia",
    "status": "Recepcionado",
    "entryTime": "15:27",
    "surgeryStart": "15:45",
    "surgeryEnd": "17:20",
    "exitTime": "17:40",
    "entryDelayMin": 18,
    "actualSurgeryMin": 95,
    "roomDurationMin": 133
  },
  {
    "id": "I0001187824",
    "date": "2026-05-26",
    "patient": "MARIO FERNANDO GARRIDO VALENZUELA",
    "age": "67a 10m 8d",
    "diagnosis": "",
    "surgery": "HEMORROIDECTOMIA (INCLUYE OTRAS OPERACIONES COMPLEMENTARIAS EN CANAL ANAL)",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Jeraldo Triantafilo Schilling (Protocolo Operatorio)",
    "surgeon": "Dra. Marisol Noriel Valdes",
    "room": "Quirofano 11",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "15:43",
    "surgeryStart": "16:15",
    "surgeryEnd": "16:35",
    "exitTime": "16:40",
    "entryDelayMin": 32,
    "actualSurgeryMin": 20,
    "roomDurationMin": 57
  },
  {
    "id": "I0001187797",
    "date": "2026-05-26",
    "patient": "BENJAMÍN ALONSO CORDERO ROJAS",
    "age": "17a 3m 25d",
    "diagnosis": "",
    "surgery": "AMIGDALECTOMIA C/S ADENOIDECTOMIA, UNI O BILATERAL",
    "specialty": "OTORRINOLARINGOLOGIA",
    "anesthetist": "Rodrigo Alejandro Villegas Lugo (Protocolo Operatorio)",
    "surgeon": "Dr. Fernando Rivas Castillo",
    "room": "Quirofano 06",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "15:52",
    "surgeryStart": "16:05",
    "surgeryEnd": "16:50",
    "exitTime": "",
    "entryDelayMin": 13,
    "actualSurgeryMin": 45,
    "roomDurationMin": ""
  },
  {
    "id": "I0001187915",
    "date": "2026-05-26",
    "patient": "TAMARA FABIOLA ARANEDA BUGUEÑO",
    "age": "36a 0m 6d",
    "diagnosis": "",
    "surgery": "BARTOLINOCISTONEOSTOMIA O EXTIRP. DE LA GLANDULA",
    "specialty": "GINECOLOGIA",
    "anesthetist": "Margarita Rojas Espinoza (Protocolo Operatorio)",
    "surgeon": "Juan Rodriguez Ticona",
    "room": "Quirofano 02",
    "type": "Cirugía Urgencia",
    "status": "Realizado",
    "entryTime": "16:13",
    "surgeryStart": "16:40",
    "surgeryEnd": "16:57",
    "exitTime": "",
    "entryDelayMin": 27,
    "actualSurgeryMin": 17,
    "roomDurationMin": ""
  },
  {
    "id": "I0001187732",
    "date": "2026-05-26",
    "patient": "JUAN MANUEL CÓRDOVA CONTRERAS",
    "age": "67a 10m 13d",
    "diagnosis": "",
    "surgery": "Adenoma o cáncer prostático, resección endoscópica desobstructiva, cualquier técnica (uni, bipolar, láser u otros)",
    "specialty": "UROLOGIA",
    "anesthetist": "",
    "surgeon": "Francisco Telayna Manrique",
    "room": "Quirofano 10",
    "type": "Cirugía Electiva",
    "status": "Realizado",
    "entryTime": "16:35",
    "surgeryStart": "17:02",
    "surgeryEnd": "18:45",
    "exitTime": "19:15",
    "entryDelayMin": 27,
    "actualSurgeryMin": 103,
    "roomDurationMin": 160
  },
  {
    "id": "I0001187726",
    "date": "2026-05-26",
    "patient": "BEATRIZ SOLEDAD ROSALES PENRROZ",
    "age": "50a 8m 10d",
    "diagnosis": "",
    "surgery": "COLECISTECTOMIA POR VIDEOLAPAROSCOPIA, PROC. COMPLETO",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Aliana Violeta Morales Ruiz (Protocolo Anestésico)",
    "surgeon": "Gonzalo Godoy Moya",
    "room": "Quirofano 09",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "16:52",
    "surgeryStart": "17:50",
    "surgeryEnd": "18:20",
    "exitTime": "18:35",
    "entryDelayMin": 58,
    "actualSurgeryMin": 30,
    "roomDurationMin": 103
  },
  {
    "id": "I0001188121",
    "date": "2026-05-26",
    "patient": "ALFONSO RODRIGO GONZÁLEZ FAÚNDEZ",
    "age": "55a 9m 25d",
    "diagnosis": "",
    "surgery": "OCLUSION INTESTINAL, TRAT. QUIR.- CON RESECCION",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Jackeline Nuñez (Protocolo Anestésico); Jackeline Nuñez (Protocolo Operatorio)",
    "surgeon": "Dr. Rodrigo Martinez Lobos",
    "room": "Quirofano 16",
    "type": "Cirugía Urgencia",
    "status": "Recepcionado",
    "entryTime": "17:00",
    "surgeryStart": "17:35",
    "surgeryEnd": "19:45",
    "exitTime": "20:30",
    "entryDelayMin": 35,
    "actualSurgeryMin": 130,
    "roomDurationMin": 210
  },
  {
    "id": "I0001187779",
    "date": "2026-05-26",
    "patient": "CORINA DEL CARMEN FARÍAS CERDA",
    "age": "77a 4m 6d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Carlos Pinto Pinto Guerrero (Protocolo Anestésico); Carlos Pinto Pinto Guerrero (Protocolo Operatorio)",
    "surgeon": "Mauricio Andres Perez Gonzales",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "17:02",
    "surgeryStart": "17:10",
    "surgeryEnd": "17:33",
    "exitTime": "17:34",
    "entryDelayMin": 8,
    "actualSurgeryMin": 23,
    "roomDurationMin": 32
  },
  {
    "id": "I0001185047",
    "date": "2026-05-26",
    "patient": "MAYCOL ANDRES TEJADA ARBOLEDA",
    "age": "30a 0m 7d",
    "diagnosis": "",
    "surgery": "Tratamiento completo de fracturas expuestas de mano o pie, c/u",
    "specialty": "TRAUMATOLOGIA Y ORTOPEDÍA",
    "anesthetist": "Gianna Muñoz (Protocolo Operatorio)",
    "surgeon": "Sebastián Pinto Padilla",
    "room": "Quirofano 05",
    "type": "Cirugía Electiva",
    "status": "Atendido",
    "entryTime": "17:10",
    "surgeryStart": "17:46",
    "surgeryEnd": "18:30",
    "exitTime": "19:00",
    "entryDelayMin": 36,
    "actualSurgeryMin": 44,
    "roomDurationMin": 110
  },
  {
    "id": "I0001187780",
    "date": "2026-05-26",
    "patient": "CLARISA FUENZALIDA RUBIO",
    "age": "94a 6m 29d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Carlos Pinto Pinto Guerrero (Protocolo Anestésico); Carlos Pinto Pinto Guerrero (Protocolo Operatorio)",
    "surgeon": "Mauricio Andres Perez Gonzales",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "17:36",
    "surgeryStart": "17:44",
    "surgeryEnd": "17:55",
    "exitTime": "17:56",
    "entryDelayMin": 8,
    "actualSurgeryMin": 11,
    "roomDurationMin": 20
  },
  {
    "id": "I0001187783",
    "date": "2026-05-26",
    "patient": "ERWIN REYES GÓMEZ",
    "age": "65a 4m 5d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Carlos Pinto Pinto Guerrero (Protocolo Anestésico); Carlos Pinto Pinto Guerrero (Protocolo Operatorio)",
    "surgeon": "Mauricio Andres Perez Gonzales",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "17:57",
    "surgeryStart": "18:02",
    "surgeryEnd": "18:11",
    "exitTime": "18:12",
    "entryDelayMin": 5,
    "actualSurgeryMin": 9,
    "roomDurationMin": 15
  },
  {
    "id": "I0001187785",
    "date": "2026-05-26",
    "patient": "BENERILDA DEL CARMEN ALBORNOZ ROMANTE",
    "age": "82a 9m 22d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Carlos Pinto Pinto Guerrero (Protocolo Anestésico); Carlos Pinto Pinto Guerrero (Protocolo Operatorio)",
    "surgeon": "Mauricio Andres Perez Gonzales",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "18:13",
    "surgeryStart": "18:20",
    "surgeryEnd": "18:31",
    "exitTime": "18:32",
    "entryDelayMin": 7,
    "actualSurgeryMin": 11,
    "roomDurationMin": 19
  },
  {
    "id": "I0001188024",
    "date": "2026-05-26",
    "patient": "BEATRIZ XIMENA ASCENCIO MUÑOZ",
    "age": "29a 7m 26d",
    "diagnosis": "",
    "surgery": "APENDICECTOMIA Y/O DREN. ABSCESO APENDICULAR (PROC. AUT.)",
    "specialty": "Sin especialidad",
    "anesthetist": "Maria Elvira DE FEREIRA Acosta de Fereira (Protocolo Operatorio)",
    "surgeon": "Becado Dr. Juan Pablo Ruiz Riquelme",
    "room": "Quirofano 04",
    "type": "Cirugía Urgencia",
    "status": "Recepcionado",
    "entryTime": "18:20",
    "surgeryStart": "18:54",
    "surgeryEnd": "19:55",
    "exitTime": "20:10",
    "entryDelayMin": 34,
    "actualSurgeryMin": 61,
    "roomDurationMin": 110
  },
  {
    "id": "I0001187786",
    "date": "2026-05-26",
    "patient": "EDILIA RAQUEL SERRANO DÍAZ",
    "age": "65a 6m 1d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Carlos Pinto Pinto Guerrero (Protocolo Anestésico); Carlos Pinto Pinto Guerrero (Protocolo Operatorio)",
    "surgeon": "Mauricio Andres Perez Gonzales",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "18:34",
    "surgeryStart": "18:42",
    "surgeryEnd": "18:51",
    "exitTime": "18:52",
    "entryDelayMin": 8,
    "actualSurgeryMin": 9,
    "roomDurationMin": 18
  },
  {
    "id": "I0001187792",
    "date": "2026-05-26",
    "patient": "MARGARITA DEL CARMEN ROJAS FARÍAS",
    "age": "69a 8m 16d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Carlos Pinto Pinto Guerrero (Protocolo Anestésico); Carlos Pinto Pinto Guerrero (Protocolo Operatorio)",
    "surgeon": "Mauricio Andres Perez Gonzales",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "18:53",
    "surgeryStart": "18:59",
    "surgeryEnd": "19:10",
    "exitTime": "19:11",
    "entryDelayMin": 6,
    "actualSurgeryMin": 11,
    "roomDurationMin": 18
  },
  {
    "id": "I0001188146",
    "date": "2026-05-26",
    "patient": "LAURA JACQUELINE LÓPEZ HORMAZÁBAL",
    "age": "26a 0m 0d",
    "diagnosis": "",
    "surgery": "CESAREA",
    "specialty": "GINECOLOGIA",
    "anesthetist": "Margarita Rojas Espinoza (Protocolo Operatorio);Cristian Aguilar (Protocolo Operatorio)",
    "surgeon": "Facundo Henriquez Lagos",
    "room": "Quirofano 03",
    "type": "Cirugía Urgencia",
    "status": "Realizado",
    "entryTime": "19:00",
    "surgeryStart": "19:17",
    "surgeryEnd": "19:50",
    "exitTime": "",
    "entryDelayMin": 17,
    "actualSurgeryMin": 33,
    "roomDurationMin": ""
  },
  {
    "id": "I0001187789",
    "date": "2026-05-26",
    "patient": "GUILLERMO SALVADOR ABARZÚA CERDA",
    "age": "86a 9m 1d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "Carlos Pinto Pinto Guerrero (Protocolo Anestésico); Carlos Pinto Pinto Guerrero (Protocolo Operatorio)",
    "surgeon": "Mauricio Andres Perez Gonzales",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "19:12",
    "surgeryStart": "19:18",
    "surgeryEnd": "19:30",
    "exitTime": "19:31",
    "entryDelayMin": 6,
    "actualSurgeryMin": 12,
    "roomDurationMin": 19
  },
  {
    "id": "I0001188113",
    "date": "2026-05-26",
    "patient": "FERNANDA MACKARENA GONZÁLEZ MUÑOZ",
    "age": "30a 4m 19d",
    "diagnosis": "",
    "surgery": "- Raspado uterino diagnóstico o terapéutico por metrorragia o por restos de aborto",
    "specialty": "Sin especialidad",
    "anesthetist": "Margarita Rojas Espinoza (Protocolo Operatorio)",
    "surgeon": "Juan Rodriguez Ticona",
    "room": "Quirofano 02",
    "type": "Cirugía Urgencia",
    "status": "Realizado",
    "entryTime": "20:50",
    "surgeryStart": "21:10",
    "surgeryEnd": "21:17",
    "exitTime": "21:22",
    "entryDelayMin": 20,
    "actualSurgeryMin": 7,
    "roomDurationMin": 32
  },
  {
    "id": "I0001188120",
    "date": "2026-05-26",
    "patient": "ARAMIS ABDIEL ENRIQUE HERRERA QUINTERO",
    "age": "14a 4m 26d",
    "diagnosis": "",
    "surgery": "COLGAJOS SIMPLES DOS O MAS",
    "specialty": "Sin especialidad",
    "anesthetist": "Marcela Verónica Ortiz Acheritogaray (Protocolo Operatorio)",
    "surgeon": "Carlos Romero Romero Encina",
    "room": "Quirofano 04",
    "type": "Cirugía Urgencia",
    "status": "Atendido",
    "entryTime": "21:20",
    "surgeryStart": "21:30",
    "surgeryEnd": "22:05",
    "exitTime": "22:18",
    "entryDelayMin": 10,
    "actualSurgeryMin": 35,
    "roomDurationMin": 58
  },
  {
    "id": "I0001187935",
    "date": "2026-05-26",
    "patient": "RAQUEL MARGOT ZAMORA ROBLES",
    "age": "54a 0m 17d",
    "diagnosis": "",
    "surgery": "ABSCESO, VACIAMIENTO Y/O DRENAJE DE SACO Y/O GLANDULA LAGRIMAL",
    "specialty": "Sin especialidad",
    "anesthetist": "Jackeline Nuñez (Protocolo Operatorio)",
    "surgeon": "Pedro Pablo Gomez Torin",
    "room": "Quirofano 16",
    "type": "Cirugía Urgencia",
    "status": "Recepcionado",
    "entryTime": "21:23",
    "surgeryStart": "21:50",
    "surgeryEnd": "22:00",
    "exitTime": "22:10",
    "entryDelayMin": 27,
    "actualSurgeryMin": 10,
    "roomDurationMin": 47
  },
  {
    "id": "I0001186266",
    "date": "2026-05-26",
    "patient": "BENJAMIN ANTONIO VELOSO GONZÁLEZ",
    "age": "22a 3m 0d",
    "diagnosis": "",
    "surgery": "OSTEOSINTESIS, FRACT. CERRADA CUBITO Y/O RADIO (CUALQ. TECN.)",
    "specialty": "TRAUMATOLOGIA Y ORTOPEDÍA",
    "anesthetist": "Jorge Lopez Pelaez (Agenda)",
    "surgeon": "Dr. Eduardo Acosta Alonso",
    "room": "Quirofano 13",
    "type": "Cirugía Electiva",
    "status": "Suspendido",
    "entryTime": "",
    "surgeryStart": "",
    "surgeryEnd": "",
    "exitTime": "",
    "entryDelayMin": 0,
    "actualSurgeryMin": "",
    "roomDurationMin": ""
  },
  {
    "id": "I0001183504",
    "date": "2026-05-26",
    "patient": "FRANCISCA OLGA MORALES #",
    "age": "91a 7m 25d",
    "diagnosis": "",
    "surgery": "OSTEOMIELITIS, LIMPIEZA QUIRURGICA",
    "specialty": "TRAUMATOLOGIA Y ORTOPEDÍA",
    "anesthetist": "Reina Garrido Trejo (Agenda)",
    "surgeon": "Dr. Walter Rojas Parra",
    "room": "Quirofano 15",
    "type": "Cirugía Electiva",
    "status": "Suspendido",
    "entryTime": "",
    "surgeryStart": "",
    "surgeryEnd": "",
    "exitTime": "",
    "entryDelayMin": 0,
    "actualSurgeryMin": "",
    "roomDurationMin": ""
  },
  {
    "id": "I0001187935",
    "date": "2026-05-26",
    "patient": "RAQUEL MARGOT ZAMORA ROBLES",
    "age": "54a 0m 17d",
    "diagnosis": "",
    "surgery": "ESCARECTOMIA- HASTA 1 % SUPERFICIE CORPORAL",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "",
    "surgeon": "Dr Alvaro Mendoza Fernandez",
    "room": "Quirofano 04",
    "type": "Cirugía Urgencia",
    "status": "Suspendido",
    "entryTime": "",
    "surgeryStart": "",
    "surgeryEnd": "",
    "exitTime": "",
    "entryDelayMin": 0,
    "actualSurgeryMin": "",
    "roomDurationMin": ""
  },
  {
    "id": "I0001182556",
    "date": "2026-05-26",
    "patient": "EVELYN TATIANA ALARCÓN BECERRA",
    "age": "41a 4m 30d",
    "diagnosis": "",
    "surgery": "PSEUDOARTROSIS C/S OSTEOSINTESIS C/S YESO HUMERO",
    "specialty": "TRAUMATOLOGIA Y ORTOPEDÍA",
    "anesthetist": "Reina Garrido Trejo (Agenda)",
    "surgeon": "Dr. Andres Castro Mercado",
    "room": "Quirofano 15",
    "type": "Cirugía Electiva",
    "status": "Suspendido",
    "entryTime": "",
    "surgeryStart": "",
    "surgeryEnd": "",
    "exitTime": "",
    "entryDelayMin": 0,
    "actualSurgeryMin": "",
    "roomDurationMin": ""
  },
  {
    "id": "I0001187774",
    "date": "2026-05-26",
    "patient": "JUAN JOSE SANCHEZ CHIRINOS",
    "age": "71a 5m 8d",
    "diagnosis": "",
    "surgery": "- FACOERESIS EXTRACAPSULAR CON IMPLANTE DE LENTE INTRAOCULAR (NO INCLUYE EL VALOR DE LA PROTESIS)",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "",
    "surgeon": "Claudio Araya Cargas",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Recepcionado",
    "entryTime": "",
    "surgeryStart": "",
    "surgeryEnd": "",
    "exitTime": "",
    "entryDelayMin": 0,
    "actualSurgeryMin": "",
    "roomDurationMin": ""
  },
  {
    "id": "I0001186152",
    "date": "2026-05-26",
    "patient": "FERNANDO MARCELO ZAPATA MUÑOZ",
    "age": "56a 5m 28d",
    "diagnosis": "",
    "surgery": "OSTEOSINTESIS, FRACT. CERRADA CUBITO Y/O RADIO (CUALQ. TECN.)",
    "specialty": "TRAUMATOLOGIA Y ORTOPEDÍA",
    "anesthetist": "Jorge Lopez Pelaez (Agenda)",
    "surgeon": "Sebastián Pinto Padilla",
    "room": "Quirofano 13",
    "type": "Cirugía Electiva",
    "status": "Suspendido",
    "entryTime": "",
    "surgeryStart": "",
    "surgeryEnd": "",
    "exitTime": "",
    "entryDelayMin": 0,
    "actualSurgeryMin": "",
    "roomDurationMin": ""
  },
  {
    "id": "I0001187776",
    "date": "2026-05-26",
    "patient": "GUILLERMO DANIEL ARANDA URRIOLA",
    "age": "75a 4m 28d",
    "diagnosis": "",
    "surgery": "GLAUCOMA, TRAT. QUIR. POR CUALQUIER TECNICA",
    "specialty": "OFTALMOLOGIA",
    "anesthetist": "",
    "surgeon": "Mauricio Andres Perez Gonzales",
    "room": "Quirofano 08",
    "type": "Cirugía Electiva",
    "status": "Agendado",
    "entryTime": "",
    "surgeryStart": "",
    "surgeryEnd": "",
    "exitTime": "",
    "entryDelayMin": 0,
    "actualSurgeryMin": "",
    "roomDurationMin": ""
  },
  {
    "id": "I0001187728",
    "date": "2026-05-26",
    "patient": "RUTH XIMENA DOMINGUAL HUENCHUPÁN",
    "age": "41a 3m 27d",
    "diagnosis": "",
    "surgery": "COLECISTECTOMIA POR VIDEOLAPAROSCOPIA, PROC. COMPLETO",
    "specialty": "CIRUGIA GENERAL",
    "anesthetist": "Aliana Violeta Morales Ruiz (Agenda)",
    "surgeon": "Gonzalo Godoy Moya",
    "room": "Quirofano 09",
    "type": "Cirugía Electiva",
    "status": "Suspendido",
    "entryTime": "",
    "surgeryStart": "",
    "surgeryEnd": "",
    "exitTime": "",
    "entryDelayMin": 0,
    "actualSurgeryMin": "",
    "roomDurationMin": ""
  }
];
